name: Generate release

on:  
  push:
    tags:
      - '*'

jobs:
   createrelease:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check if pre-release
        id: check_prerelease
        run: |
          LATEST=`cat versions.json | jq -r '.latest.version'`

          if [[ "${{ env.RELEASE_VERSION }}" == "v${LATEST}" ]]; then
              echo "PRERELEASE=false" >> $GITHUB_OUTPUT
          else
              echo "PRERELEASE=true" >> $GITHUB_OUTPUT
          fi

      - name: Zip contents
        run: |

          # Zip resource pack
          cd resource_pack/
          zip -r resource_pack.zip .
          mv resource_pack.zip ../
          cd ..

          # Zip behaviour pack
          cd behavior_pack/
          zip -r behavior_pack.zip .
          mv behavior_pack.zip ../
          cd ..

          # Zip documentation
          cd documentation/
          zip -r documentation.zip .
          mv documentation.zip ../
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ steps.check_prerelease.outputs.PRERELEASE }}
          fail_on_unmatched_files: true
          files: |
            resource_pack.zip
            behavior_pack.zip
            documentation.zip

      - name: Cleanup
        run: |
          rm resource_pack.zip
          rm behavior_pack.zip
          rm documentation.zip    
